openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 0.0.1
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /todos:
    get:
      summary: List all todos
      operationId: getTodoList
      responses:
        "200":
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - is_completed
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        is_completed:
          type: boolean
